docker.container-name=postgres-branches-scratchpad
docker.image=postgres:16-alpine
postgres.user=postgres
postgres.password=postgres
postgres.admin-database=postgres
postgres.host-port=55432
postgres.dialect=postgresql
service.port=47615
metadata.host=localhost
metadata.port=5432
metadata.user=postgres
metadata.password=postgres
metadata.admin-database=postgres
metadata.database=dbgit_metadata
metadata.dialect=postgresql
